#!/bin/bash

CONNECTED_MONITORS=$(xrandr | grep ' connected' | wc -l)

if [[ $CONNECTED_MONITORS -gt 1 ]]; then
	setxkbmap -option
else
	xmodmap ~/.xmodmaprc
fi

echo "$CONNECTED_MONITORS connected"

nitrogen --restore
