#!/bin/bash

NITROGEN_HOME="$HOME/.config/nitrogen"
NITROGEN_BG="$NITROGEN_HOME/bg-saved.cfg"

# try to detect profile
PROFILE=$(autorandr 2>&1| grep detected |awk '{ print $1 }')
[[ -n "$PROFILE" ]] || exit 1

PROFILE_BG_FILE="bg-saved.$PROFILE.cfg"
PROFILE_BG="$NITROGEN_HOME/$PROFILE_BG_FILE"

CP=$(which cp)
MV=$(which mv)
UNLINK=$(which unlink)
NITROGEN=$(which nitrogen)

# save background for detected profile
if [[ $1 = 'savebg' ]]; then
    # nitrogen config doesn't exist, instruct to run it first
    if [[ ! -f "$NITROGEN_BG" ]]; then
        echo "wallpaper: you need to first run 'nitrogen' and set your wallpapers"
        exit 2
    fi
    # nitrogen config exists but is broken symlink, just remove it and instruct to run it first
    if [ ! -e "$NITROGEN_BG" ] ; then
        $UNLINK "$NITROGEN_BG"
        echo "wallpaper: you need to first run 'nitrogen' and set your wallpapers (config was broken)"
        exit 3
    fi

    $CP -L "$NITROGEN_BG" "$PROFILE_BG"

# load background for detected profile
else
    # we have some profile background config for this setup
    if [[ -f "$PROFILE_BG" ]]; then
        # nitrogen original file exists and not symlink
        if [[ -f "$NITROGEN_BG" ]] && [[ ! -L "$NITROGEN_BG" ]]; then
            echo "wallpaper: Backing up nitrogen saved bg to $NITROGEN_BG.backup" 
            $MV "$NITROGEN_BG" "$NITROGEN_BG".backup
        fi
        
        # set symlink
        echo "wallpaper: Found saved wallpaper for profile $PROFILE - changing"
        ln -f -s "$PROFILE_BG_FILE" "$NITROGEN_BG"
        # call nitrogen
        $NITROGEN --restore
    else
        echo "wallpaper: No saved wallpaper found for profile $PROFILE"
    fi
fi

